//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanLaptrinhweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dangnhac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dangnhac()
        {
            this.Nhacs = new HashSet<Nhac>();
        }
    
        public int MaDangnhac { get; set; }
        public string TenDangnhac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhac> Nhacs { get; set; }
    }
}
